# Generated by Django 4.1.3 on 2022-11-20 21:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdministrationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_oauth_json_credentials', models.JSONField(blank=True, null=True, verbose_name='Google OAuth Credentials - JSON (Copy and Paste)')),
                ('google_service_account_auth_json_credentials', models.JSONField(blank=True, null=True, verbose_name='Google Service Account Credentials - JSON (Copy and Paste)')),
                ('smtp_enable_email_notifications', models.BooleanField(default=False, verbose_name='Do you want to enable email notifications (on migration completion)? If so, the below fields will be required.')),
                ('smtp_username', models.CharField(blank=True, max_length=64, null=True, verbose_name='SMTP Username')),
                ('smtp_password', models.CharField(blank=True, max_length=64, null=True, verbose_name='SMTP Password')),
                ('smtp_port', models.IntegerField(blank=True, default=587, null=True, verbose_name='SMTP Port (Default is 587)')),
                ('smtp_server', models.CharField(blank=True, max_length=128, null=True, verbose_name='SMTP Server / Host (e.g. smtp.office365.com)')),
                ('smtp_subject', models.TextField(blank=True, default='Google Drive to SharePoint Migration Complete', null=True)),
                ('twilio_enable_sms_notifications', models.BooleanField(default=False, verbose_name='Do you want to enable SMS notifications for users? If so, the Twilio settings below will be required.')),
                ('twilio_messaging_service_sid', models.CharField(blank=True, max_length=32, null=True, verbose_name='Provide your Twilio Messaging Service SID')),
                ('twilio_account_sid', models.CharField(blank=True, max_length=32, null=True, verbose_name='Provide your Twilio Account SID (from your Twilio account dashboard)')),
                ('twilio_account_auth_token', models.CharField(blank=True, max_length=32, null=True, verbose_name='Provide your Twilio Account Auth Token (from your Twilio account dashboard)')),
            ],
            options={
                'verbose_name': 'Administration Settings',
                'verbose_name_plural': 'Administration Settings',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timezone', models.CharField(default='UTC', max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
            },
        ),
        migrations.CreateModel(
            name='Migration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('lastmod', models.DateTimeField(auto_now=True)),
                ('num_files', models.IntegerField(default=0)),
                ('num_folders', models.IntegerField(default=0)),
                ('total_size', models.CharField(default='0', max_length=32)),
                ('start_timestamp', models.DateTimeField(auto_now_add=True)),
                ('end_timestamp', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Migration',
                'verbose_name_plural': 'Migrations',
            },
        ),
    ]
