# Generated by Django 4.1.3 on 2022-11-19 20:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AdministrationSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("google_oauth_client_id", models.CharField(max_length=100)),
                ("google_oauth_project_id", models.CharField(max_length=50)),
                ("google_oauth_auth_uri", models.URLField()),
                ("google_oauth_token_uri", models.URLField()),
                ("google_oauth_auth_provider_x509_cert_url", models.URLField()),
                ("google_oauth_auth_client_secret", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Migration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("lastmod", models.DateTimeField(auto_now=True)),
                ("num_files", models.IntegerField(default=0)),
                ("num_folders", models.IntegerField(default=0)),
                ("total_size", models.CharField(default="0", max_length=32)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AdministrationSettings_ListAttributeItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "list_type",
                    models.CharField(
                        choices=[
                            ("GARU", "Google OAuth Redirect URI"),
                            ("GAJO", "Google OAuth JS Origin"),
                        ],
                        default="GARU",
                        max_length=5,
                    ),
                ),
                (
                    "administration_settings",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="web.administrationsettings",
                    ),
                ),
            ],
        ),
    ]
