# Generated by Django 4.1.3 on 2022-11-21 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrationsettings',
            name='organization_name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
