# Generated by Django 4.1.3 on 2022-11-21 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_administrationsettings_organization_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrationsettings',
            name='azure_ad_client_id',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Azure AD App Registration - Application/Client ID'),
        ),
        migrations.AddField(
            model_name='administrationsettings',
            name='azure_ad_client_secret',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Azure AD App Registration - Client Secret'),
        ),
        migrations.AddField(
            model_name='administrationsettings',
            name='azure_ad_tenant_id',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Azure AD App Registration - (Directory) Tenant ID'),
        ),
    ]
