# Generated by Django 4.1.3 on 2022-11-20 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_administrationsettings_google_service_account_auth_client_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='administrationsettings',
            name='smtp_send_email_notifications',
        ),
        migrations.AddField(
            model_name='administrationsettings',
            name='smtp_enable_email_notifications',
            field=models.BooleanField(default=False, verbose_name='Do you want to enable email notifications (on migration completion)? If so, the below fields will be required.'),
        ),
        migrations.AddField(
            model_name='administrationsettings',
            name='twilio_account_auth_token',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Provide your Twilio Account Auth Token (from your Twilio account dashboard)'),
        ),
        migrations.AddField(
            model_name='administrationsettings',
            name='twilio_account_sid',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Provide your Twilio Account SID (from your Twilio account dashboard)'),
        ),
        migrations.AddField(
            model_name='administrationsettings',
            name='twilio_enable_sms_notifications',
            field=models.BooleanField(default=False, verbose_name='Do you want to enable SMS notifications for users? If so, the Twilio settings below will be required.'),
        ),
        migrations.AddField(
            model_name='administrationsettings',
            name='twilio_messaging_service_sid',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Provide your Twilio Messaging Service SID'),
        ),
        migrations.AlterField(
            model_name='administrationsettings',
            name='google_oauth_auth_client_secret',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Google Service Account - Client Secret'),
        ),
        migrations.AlterField(
            model_name='administrationsettings',
            name='google_oauth_auth_provider_x509_cert_url',
            field=models.URLField(blank=True, null=True, verbose_name='Google Service Account - Auth Provider X509 Cert URL'),
        ),
        migrations.AlterField(
            model_name='administrationsettings',
            name='google_oauth_auth_uri',
            field=models.URLField(blank=True, null=True, verbose_name='Google Service Account - Auth URI'),
        ),
        migrations.AlterField(
            model_name='administrationsettings',
            name='google_oauth_client_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Google Service Account - Client ID'),
        ),
        migrations.AlterField(
            model_name='administrationsettings',
            name='google_oauth_project_id',
            field=models.CharField(max_length=50, verbose_name='Google Service Account - Project ID'),
        ),
        migrations.AlterField(
            model_name='administrationsettings',
            name='google_oauth_token_uri',
            field=models.URLField(blank=True, null=True, verbose_name='Google Service Account - Token URI'),
        ),
        migrations.AlterField(
            model_name='administrationsettings',
            name='google_service_account_auth_client_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Google Service Account - Client Email'),
        ),
        migrations.AlterField(
            model_name='administrationsettings',
            name='google_service_account_auth_client_id',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Google Service Account - Client ID'),
        ),
        migrations.AlterField(
            model_name='administrationsettings',
            name='google_service_account_auth_private_key',
            field=models.TextField(blank=True, null=True, verbose_name='Google Service Account - Private Key'),
        ),
        migrations.AlterField(
            model_name='administrationsettings',
            name='google_service_account_auth_private_key_id',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Google Service Account - Private Key ID'),
        ),
        migrations.AlterField(
            model_name='administrationsettings',
            name='google_service_account_auth_project_id',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Google Service Account - Project ID'),
        ),
        migrations.AlterField(
            model_name='administrationsettings',
            name='smtp_password',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='SMTP Password'),
        ),
        migrations.AlterField(
            model_name='administrationsettings',
            name='smtp_port',
            field=models.IntegerField(blank=True, default=587, null=True, verbose_name='SMTP Port (Default is 587)'),
        ),
        migrations.AlterField(
            model_name='administrationsettings',
            name='smtp_server',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='SMTP Server / Host (e.g. smtp.office365.com)'),
        ),
        migrations.AlterField(
            model_name='administrationsettings',
            name='smtp_username',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='SMTP Username'),
        ),
    ]
