# Generated by Django 4.1.3 on 2022-11-23 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_administrationsettings_azure_ad_client_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='migration',
            name='complete',
            field=models.BooleanField(default=False, verbose_name='Whether the migration is complete'),
        ),
        migrations.AddField(
            model_name='migration',
            name='completion_notification_sent',
            field=models.BooleanField(default=False, verbose_name='Whether a post-completion notification has been sent'),
        ),
        migrations.AddField(
            model_name='migration',
            name='google_source',
            field=models.JSONField(blank=True, null=True, verbose_name='JSON object including at minimum id, name, or type as keys describing the source folder or shared drive being migrated. Type can be "shared_drive" or "folder"'),
        ),
        migrations.AddField(
            model_name='migration',
            name='initial_source_scan_complete',
            field=models.BooleanField(default=False, verbose_name='Whether the initial scan of the source data is complete'),
        ),
        migrations.AddField(
            model_name='migration',
            name='local_temp_dir',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Local directory path where files are temporarily housed during migration'),
        ),
        migrations.AddField(
            model_name='migration',
            name='state',
            field=models.CharField(choices=[('NEW', 'New'), ('READY', 'Ready'), ('PROCESSING', 'Processing'), ('STOPPING', 'Stopping'), ('FAILED', 'Failed'), ('COMPLETE', 'Complete')], db_index=True, default='NEW', max_length=20),
        ),
        migrations.AddField(
            model_name='migration',
            name='target',
            field=models.JSONField(blank=True, default={}, null=True, verbose_name='Information describing either a SharePoint Site Folder in a Document Library or a OneDrive Folder for the user OneDrive account'),
        ),
        migrations.AlterField(
            model_name='migration',
            name='end_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
