# Generated by Django 4.1.3 on 2022-11-25 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_remove_migration_flattened_google_files_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrationsettings',
            name='require_idp_login',
            field=models.BooleanField(default=False, verbose_name='Whether to require login via the IdP (AKA whether to require SSO). If true, local login form will be disabled.'),
        ),
    ]
