# Generated by Django 4.1.3 on 2022-11-26 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_administrationsettings_onedrive_email_notification_template_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrationsettings',
            name='google_oauth_json_credentials',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='Google OAuth Credentials - JSON (Copy and Paste)'),
        ),
        migrations.AlterField(
            model_name='administrationsettings',
            name='google_service_account_auth_json_credentials',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='Google Service Account Credentials - JSON (Copy and Paste)'),
        ),
        migrations.AlterField(
            model_name='migration',
            name='google_source',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='JSON object including at minimum id, name, or type as keys describing the source folder or shared drive being migrated. Type can be "shared_drive" or "folder"'),
        ),
        migrations.AlterField(
            model_name='migration',
            name='source_data_scan_result',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='High-level stats about the migration to be run based on scanning the source data to be migrated'),
        ),
        migrations.AlterField(
            model_name='migration',
            name='target',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='Information describing either a SharePoint Site Folder in a Document Library or a OneDrive Folder for the user OneDrive account'),
        ),
    ]
