name: Django - Continuous Integration
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  Testing:
    runs-on: ubuntu-latest # operating system your code will run on
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run Database Migrations
        env:
          # Dummy secret value
          SECRET_KEY: c48155301fef301d64dafb707c3e12c8fb2d9f3cf3fee6e51e
        run: |
          cd GoogleSharePointMigrationAssistant
          python manage.py makemigrations web 
          python manage.py migrate web
      - name: Run tests
        env:
          # Dummy secret value
          SECRET_KEY: c48155301fef301d64dafb707c3e12c8fb2d9f3cf3fee6e51e
        run: |
          cd GoogleSharePointMigrationAssistant
          python manage.py test
